// Generated by gencpp from file service_example/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SERVICE_EXAMPLE_MESSAGE_ADDTWOINTS_H
#define SERVICE_EXAMPLE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <service_example/AddTwoIntsRequest.h>
#include <service_example/AddTwoIntsResponse.h>


namespace service_example
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace service_example


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_example::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::service_example::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::service_example::AddTwoInts > {
  static const char* value()
  {
    return "service_example/AddTwoInts";
  }

  static const char* value(const ::service_example::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::service_example::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::service_example::AddTwoInts > 
template<>
struct MD5Sum< ::service_example::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_example::AddTwoInts >::value();
  }
  static const char* value(const ::service_example::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_example::AddTwoIntsRequest> should match 
// service_traits::DataType< ::service_example::AddTwoInts > 
template<>
struct DataType< ::service_example::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::service_example::AddTwoInts >::value();
  }
  static const char* value(const ::service_example::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_example::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::service_example::AddTwoInts > 
template<>
struct MD5Sum< ::service_example::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_example::AddTwoInts >::value();
  }
  static const char* value(const ::service_example::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_example::AddTwoIntsResponse> should match 
// service_traits::DataType< ::service_example::AddTwoInts > 
template<>
struct DataType< ::service_example::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::service_example::AddTwoInts >::value();
  }
  static const char* value(const ::service_example::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_EXAMPLE_MESSAGE_ADDTWOINTS_H
